### ISSUE TITLE
[BUG]: Late Error checks for Form validation

### ISSUE THREAD

**Issue by jamm59** [nutrition-monitoring-system/nhms#10]
**Issue Description:**
The form validation functionality on the website appears to be malfunctioning. Specifically, in the multiform section of the registration page, after entering personal information (such as name, email, and password) and clicking "Next," the expected behavior is to return to the first section of the multiform if there are any invalid inputs or errors.

**Steps to Reproduce:**
1. Navigate to the registration page on the website.
2. Fill out the form with invalid inputs, such as an email address without the '@' symbol, a password that is too short, or a username that is already taken.
3. Click on the "Next" button.
4. Observe that it proceeds to the next page without checking for any errors.

**Actual Result:**
The website fails to validate the input fields and instead progresses to the next page, neglecting to address the invalid inputs or errors.

**Comment by Lateef9** [comment]
Hii, I was trying to run the projects and it seems scripts are missing

**Comment by jamm59** [comment]
Fixed
