### ISSUE TITLE
[TODO]: Fix the README.md

### ISSUE THREAD

**Issue by harrykeeran12** [nutrition-monitoring-system/nhms#25]
Add a README.md which contains the items Bruce wanted us to do.

**Comment by harrykeeran12** [comment]
For the dependencies, the user normally can just use the `package-lock.json` file.

For the sample data files, these could probably be provided but would require some sort of comment telling the user to create an `.env` file in the `src` folder, and to install postgres:

Their `.env` file would look like `DATABASE_URL = postgresql://USER:PASSWORD@HOST:PORT/DATABASE` where they would replace USER, PASSWORD, HOST, PORT and DATABASE with their configuration with the specific features. 

- [ ] Could you add a license? 
- [ ] Could you also probably add a Code of Conduct(for contributing)? We want to make this as futureproof as possible, I guess.

**Comment by harrykeeran12** [comment]
@cbraidwood is this completed? I moved it to the board, but I have no clue if this is actually done or not.

**Comment by cbraidwood** [comment]
> @cbraidwood is this completed? I moved it to the board, but I have no clue if this is actually done or not.

For it to be complete we just need to add the sample data files section which might be a bit sketchy

**Comment by harrykeeran12** [comment]
> > @cbraidwood is this completed? I moved it to the board, but I have no clue if this is actually done or not.
> 
> For it to be complete we just need to add the sample data files section which might be a bit sketchy

Did you write a code of conduct?
 I think adding the sample data files as a separate item in the Product Backlog and closing this would be a good idea.

**Comment by harrykeeran12** [comment]
I'll close this once we get some information about the license.

**Comment by harrykeeran12** [comment]
We can add this to the bottom of the README.md or add this to a license file. 


This work is licensed under Attribution-NonCommercial-NoDerivatives 4.0 International. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/
