### ISSUE TITLE
[TODO] Terms and Conditions not available yet

### ISSUE THREAD

**Issue by jamm59** [nutrition-monitoring-system/nhms#7]
**Description**
 The Terms and Conditions page of the website is not accessible to the users. This is a major issue as it affects the user’s trust and confidence in the website and its services. Users should be able to read and agree to the Terms and Conditions before using the website.

**Expected Behavior:** 
The Terms and Conditions page should display the legal agreement between the website and the users, outlining the rights and obligations of both parties. The page should be clear, concise, and easy to understand. The page should also provide a way for users to accept or decline the Terms and Conditions.

**Actual Behavior:** 
The Terms and Conditions page is not available yet.

**Comment by harrykeeran12** [comment]
We also need to add the TOC to the user login screen. @cbraidwood could you also find a way so that our data could be GDPR compliant? Maybe updating the TOC to add things about privacy too?

**Comment by cbraidwood** [comment]
Terms and conditions and privacy policy documents are now in the frontend branch. We just need to make it look pretty and change it to a js file.
