### ISSUE TITLE
[TODO] Blog section of the site not available yet

### ISSUE THREAD

**Issue by jamm59** [nutrition-monitoring-system/nhms#8]
**Issue Description:** The blog page of the website is not any displaying. 

**Expected Behavior:** The blog page should display the posts in a grid layout, with each post having a title, a summary, an image, and a read more button. The images should be resized and cropped to fit the grid. The pagination should allow users to go to the next or previous page of posts, or jump to a specific page number.

**Actual Behavior:** The blog page takes the user to an empty page

**Comment by harrykeeran12** [comment]
We should probably redirect the application to a 404 error.

**Comment by jamm59** [comment]
Complete Now
Header
![image](https://github.com/nutrition-monitoring-system/nhms/assets/52214276/56f15777-ce4f-4cba-b04e-c912f1413cab)
Rest of the Page
![image](https://github.com/nutrition-monitoring-system/nhms/assets/52214276/a7b82925-ec81-4441-8083-a493f9efff93)
