### ISSUE TITLE
[BUG]: File upload not working 

### ISSUE THREAD

**Issue by jamm59** [nutrition-monitoring-system/nhms#9]
File upload not working in the last section of the registration process (The Food Log section)

**Comment by harrykeeran12** [comment]
Using [indexedDB](https://dev.to/tqbit/how-to-use-indexeddb-to-store-images-and-other-files-in-your-browser-51fm) to store the images.

**Comment by harrykeeran12** [comment]
- [ ] Create a carousel wrapper(find one online)
- [ ] Create buttons for editing and deleting a photo inside a `PhotoLog` component
- [ ] Add a photo button under the log buttons already(I'll do this)
- [ ] Create the form page in `app`to add a photo, with the date(make sure its not over the current date) 
@CodingEloise if you need any help just ask me or @jamm59
